//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFirmaCagri.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFirmalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFirmalar()
        {
            this.tblCagrilar = new HashSet<tblCagrilar>();
            this.tblMesajlar = new HashSet<tblMesajlar>();
            this.tblMesajlar1 = new HashSet<tblMesajlar>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Yetkili { get; set; }
        public string mail { get; set; }
        public string Telefon { get; set; }
        public string Sektor { get; set; }
        public string Sifre { get; set; }
        public string Gorsel { get; set; }
        public string İl { get; set; }
        public string İlce { get; set; }
        public string Adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCagrilar> tblCagrilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMesajlar> tblMesajlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMesajlar> tblMesajlar1 { get; set; }
    }
}
